// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/admin" | "/admin/cms" | "/admin/cms/[pageId]" | "/admin/login" | "/admin/messages" | "/careers" | "/contact" | "/contribute" | "/elevated-pathways" | "/home-family-care" | "/partners" | "/partners/al-khair" | "/partners/cef" | "/partners/generations" | "/partners/hunar" | "/qarz-e-hasna" | "/success-stories"
type AppRouteHandlerRoutes = "/api/admin/audit-logs" | "/api/admin/content" | "/api/admin/hired-candidates" | "/api/admin/interview-candidates" | "/api/admin/job-responses" | "/api/admin/mark-hired" | "/api/admin/mark-interview" | "/api/admin/messages" | "/api/admin/upload" | "/api/admin/volunteers/respond" | "/api/auth/login" | "/api/auth/logout" | "/api/auth/session" | "/api/candidates" | "/api/contact" | "/api/jobs" | "/api/jobs/[jobId]" | "/api/jobs/[jobId]/apply" | "/api/send-interview-email" | "/api/volunteers"
type PageRoutes = never
type LayoutRoutes = "/" | "/about" | "/admin" | "/careers" | "/contact" | "/contribute" | "/elevated-pathways" | "/home-family-care" | "/partners" | "/partners/al-khair" | "/partners/cef" | "/partners/generations" | "/partners/hunar" | "/qarz-e-hasna" | "/success-stories"
type RedirectRoutes = "/application-process"
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/admin": {}
  "/admin/cms": {}
  "/admin/cms/[pageId]": { "pageId": string; }
  "/admin/login": {}
  "/admin/messages": {}
  "/api/admin/audit-logs": {}
  "/api/admin/content": {}
  "/api/admin/hired-candidates": {}
  "/api/admin/interview-candidates": {}
  "/api/admin/job-responses": {}
  "/api/admin/mark-hired": {}
  "/api/admin/mark-interview": {}
  "/api/admin/messages": {}
  "/api/admin/upload": {}
  "/api/admin/volunteers/respond": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/session": {}
  "/api/candidates": {}
  "/api/contact": {}
  "/api/jobs": {}
  "/api/jobs/[jobId]": { "jobId": string; }
  "/api/jobs/[jobId]/apply": { "jobId": string; }
  "/api/send-interview-email": {}
  "/api/volunteers": {}
  "/application-process": {}
  "/careers": {}
  "/contact": {}
  "/contribute": {}
  "/elevated-pathways": {}
  "/home-family-care": {}
  "/partners": {}
  "/partners/al-khair": {}
  "/partners/cef": {}
  "/partners/generations": {}
  "/partners/hunar": {}
  "/qarz-e-hasna": {}
  "/success-stories": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/about": never
  "/admin": never
  "/careers": never
  "/contact": never
  "/contribute": never
  "/elevated-pathways": never
  "/home-family-care": never
  "/partners": never
  "/partners/al-khair": never
  "/partners/cef": never
  "/partners/generations": never
  "/partners/hunar": never
  "/qarz-e-hasna": never
  "/success-stories": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
