// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../../src/app/(marketing)/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../../../src/app/(marketing)/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(marketing)/careers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/careers">> = Specific
  const handler = {} as typeof import("../../../../src/app/(marketing)/careers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(marketing)/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../../../src/app/(marketing)/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(marketing)/contribute/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contribute">> = Specific
  const handler = {} as typeof import("../../../../src/app/(marketing)/contribute/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(marketing)/elevated-pathways/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/elevated-pathways">> = Specific
  const handler = {} as typeof import("../../../../src/app/(marketing)/elevated-pathways/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(marketing)/home-family-care/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/home-family-care">> = Specific
  const handler = {} as typeof import("../../../../src/app/(marketing)/home-family-care/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(marketing)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../../src/app/(marketing)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(marketing)/partners/al-khair/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partners/al-khair">> = Specific
  const handler = {} as typeof import("../../../../src/app/(marketing)/partners/al-khair/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(marketing)/partners/cef/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partners/cef">> = Specific
  const handler = {} as typeof import("../../../../src/app/(marketing)/partners/cef/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(marketing)/partners/generations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partners/generations">> = Specific
  const handler = {} as typeof import("../../../../src/app/(marketing)/partners/generations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(marketing)/partners/hunar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partners/hunar">> = Specific
  const handler = {} as typeof import("../../../../src/app/(marketing)/partners/hunar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(marketing)/partners/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partners">> = Specific
  const handler = {} as typeof import("../../../../src/app/(marketing)/partners/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(marketing)/qarz-e-hasna/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/qarz-e-hasna">> = Specific
  const handler = {} as typeof import("../../../../src/app/(marketing)/qarz-e-hasna/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(marketing)/success-stories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/success-stories">> = Specific
  const handler = {} as typeof import("../../../../src/app/(marketing)/success-stories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/admin/cms/[pageId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/cms/[pageId]">> = Specific
  const handler = {} as typeof import("../../../../src/app/admin/cms/[pageId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/admin/cms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/cms">> = Specific
  const handler = {} as typeof import("../../../../src/app/admin/cms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/admin/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/login">> = Specific
  const handler = {} as typeof import("../../../../src/app/admin/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/admin/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/messages">> = Specific
  const handler = {} as typeof import("../../../../src/app/admin/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/admin/audit-logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/audit-logs">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/admin/audit-logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/admin/content/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/content">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/admin/content/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/admin/hired-candidates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/hired-candidates">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/admin/hired-candidates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/admin/interview-candidates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/interview-candidates">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/admin/interview-candidates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/admin/job-responses/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/job-responses">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/admin/job-responses/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/admin/mark-hired/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/mark-hired">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/admin/mark-hired/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/admin/mark-interview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/mark-interview">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/admin/mark-interview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/admin/messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/messages">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/admin/messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/admin/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/upload">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/admin/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/admin/volunteers/respond/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/volunteers/respond">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/admin/volunteers/respond/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/auth/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/session">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/auth/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/candidates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/candidates">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/candidates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/contact/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contact">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/contact/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/jobs/[jobId]/apply/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/jobs/[jobId]/apply">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/jobs/[jobId]/apply/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/jobs/[jobId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/jobs/[jobId]">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/jobs/[jobId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/jobs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/jobs">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/jobs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/send-interview-email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/send-interview-email">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/send-interview-email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/volunteers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/volunteers">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/volunteers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../../src/app/(marketing)/about/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/about">> = Specific
  const handler = {} as typeof import("../../../../src/app/(marketing)/about/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(marketing)/careers/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/careers">> = Specific
  const handler = {} as typeof import("../../../../src/app/(marketing)/careers/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(marketing)/contact/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../../../src/app/(marketing)/contact/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(marketing)/contribute/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/contribute">> = Specific
  const handler = {} as typeof import("../../../../src/app/(marketing)/contribute/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(marketing)/elevated-pathways/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/elevated-pathways">> = Specific
  const handler = {} as typeof import("../../../../src/app/(marketing)/elevated-pathways/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(marketing)/home-family-care/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/home-family-care">> = Specific
  const handler = {} as typeof import("../../../../src/app/(marketing)/home-family-care/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(marketing)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../../src/app/(marketing)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(marketing)/partners/al-khair/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/partners/al-khair">> = Specific
  const handler = {} as typeof import("../../../../src/app/(marketing)/partners/al-khair/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(marketing)/partners/cef/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/partners/cef">> = Specific
  const handler = {} as typeof import("../../../../src/app/(marketing)/partners/cef/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(marketing)/partners/generations/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/partners/generations">> = Specific
  const handler = {} as typeof import("../../../../src/app/(marketing)/partners/generations/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(marketing)/partners/hunar/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/partners/hunar">> = Specific
  const handler = {} as typeof import("../../../../src/app/(marketing)/partners/hunar/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(marketing)/partners/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/partners">> = Specific
  const handler = {} as typeof import("../../../../src/app/(marketing)/partners/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(marketing)/qarz-e-hasna/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/qarz-e-hasna">> = Specific
  const handler = {} as typeof import("../../../../src/app/(marketing)/qarz-e-hasna/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(marketing)/success-stories/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/success-stories">> = Specific
  const handler = {} as typeof import("../../../../src/app/(marketing)/success-stories/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
